const sneakers = [
    { id: 1, brand: "Nike", name: "Air Jordan 1 Retro High OG", color: "Negro/Rojo", size: "38-46", price: 95.00, rating: 4.9, searchQuery: "air jordan 1 retro high og" },
    { id: 2, brand: "Nike", name: "Nike Air Force 1 Classic", color: "Blanco", size: "35-47", price: 54.99, rating: 4.8, searchQuery: "nike air force 1" },
    { id: 3, brand: "Nike", name: "Nike Air Max 90", color: "Gris/Blanco", size: "35-47", price: 75.00, rating: 4.7, searchQuery: "nike air max 90" },
    { id: 4, brand: "Nike", name: "Nike Cortez Classic", color: "Rojo/Blanco", size: "36-46", price: 49.99, rating: 4.6, searchQuery: "nike cortez" },
    { id: 5, brand: "Nike", name: "Nike Blazer Mid Vintage", color: "Naranja", size: "36-46", price: 59.99, rating: 4.5, searchQuery: "nike blazer" },
    { id: 6, brand: "Nike", name: "Nike Dunk High", color: "Azul marino", size: "35-47", price: 70.00, rating: 4.8, searchQuery: "nike dunk high" },
    { id: 7, brand: "Nike", name: "Nike React Infinity Run", color: "Blanco", size: "36-47", price: 85.00, rating: 4.7, searchQuery: "nike react infinity" },
    { id: 8, brand: "Nike", name: "Nike Air Vapormax", color: "Negro", size: "35-47", price: 95.00, rating: 4.6, searchQuery: "nike air vapormax" },
    { id: 9, brand: "Nike", name: "Nike PG 5", color: "Blanco/Azul", size: "40-47", price: 75.00, rating: 4.7, searchQuery: "nike pg 5" },
    { id: 10, brand: "Nike", name: "Nike LeBron 18", color: "Negro/Oro", size: "40-47", price: 95.00, rating: 4.8, searchQuery: "nike lebron 18" },
    { id: 11, brand: "Adidas", name: "Adidas Ultra Boost 21", color: "Negro", size: "35-47", price: 100.00, rating: 4.9, searchQuery: "adidas ultraboost" },
    { id: 12, brand: "Adidas", name: "Adidas Stan Smith", color: "Blanco/Verde", size: "35-47", price: 44.99, rating: 4.6, searchQuery: "adidas stan smith" },
    { id: 13, brand: "Adidas", name: "Adidas NMD R1", color: "Gris", size: "35-47", price: 70.00, rating: 4.7, searchQuery: "adidas nmd r1" },
    { id: 14, brand: "Adidas", name: "Adidas Superstar", color: "Blanco/Negro", size: "35-47", price: 49.99, rating: 4.5, searchQuery: "adidas superstar" },
    { id: 15, brand: "Adidas", name: "Adidas Yeezy 350", color: "Sesame", size: "36-47", price: 115.00, rating: 4.9, searchQuery: "yeezy 350" },
    { id: 16, brand: "Adidas", name: "Adidas EQT Support", color: "Negro", size: "35-47", price: 75.00, rating: 4.6, searchQuery: "adidas eqt support" },
    { id: 17, brand: "Adidas", name: "Adidas ZX 500", color: "Blanco/Rojo", size: "35-47", price: 39.99, rating: 4.4, searchQuery: "adidas zx 500" },
    { id: 18, brand: "Adidas", name: "Adidas Gazelle", color: "Azul", size: "35-47", price: 49.99, rating: 4.5, searchQuery: "adidas gazelle" },
    { id: 19, brand: "Adidas", name: "Adidas Forum Low", color: "Blanco", size: "35-47", price: 54.99, rating: 4.6, searchQuery: "adidas forum" },
    { id: 20, brand: "Adidas", name: "Adidas Nite Jogger", color: "Negro/Gris", size: "35-47", price: 65.00, rating: 4.5, searchQuery: "adidas nite jogger" },
    { id: 21, brand: "Puma", name: "Puma RS-X", color: "Blanco/Negro", size: "35-47", price: 59.99, rating: 4.5, searchQuery: "puma rs-x" },
    { id: 22, brand: "Puma", name: "Puma Suede Classic", color: "Rojo", size: "35-47", price: 44.99, rating: 4.4, searchQuery: "puma suede" },
    { id: 23, brand: "Puma", name: "Puma Future Rider", color: "Blanco/Azul", size: "35-47", price: 49.99, rating: 4.5, searchQuery: "puma future rider" },
    { id: 24, brand: "Puma", name: "Puma Clyde Premium", color: "Negro", size: "36-47", price: 70.00, rating: 4.6, searchQuery: "puma clyde" },
    { id: 25, brand: "Puma", name: "Puma Cali", color: "Blanco", size: "35-47", price: 54.99, rating: 4.4, searchQuery: "puma cali" },
    { id: 26, brand: "Puma", name: "Puma Roma", color: "Gris", size: "35-47", price: 39.99, rating: 4.3, searchQuery: "puma roma" },
    { id: 27, brand: "Puma", name: "Puma Sky Modern", color: "Blanco/Negro", size: "35-47", price: 44.99, rating: 4.4, searchQuery: "puma sky" },
    { id: 28, brand: "Puma", name: "Puma Basket Heart", color: "Rosa", size: "35-46", price: 49.99, rating: 4.5, searchQuery: "puma basket heart" },
    { id: 29, brand: "Puma", name: "Puma Court Rider", color: "Negro/Blanco", size: "36-47", price: 59.99, rating: 4.5, searchQuery: "puma court rider" },
    { id: 30, brand: "Puma", name: "Puma Deviate Nitro", color: "Amarillo", size: "35-47", price: 75.00, rating: 4.6, searchQuery: "puma deviate" },
    { id: 31, brand: "Converse", name: "Converse Chuck Taylor All Star", color: "Blanco", size: "35-47", price: 34.99, rating: 4.3, searchQuery: "converse chuck taylor" },
    { id: 32, brand: "Converse", name: "Converse Chuck 70 High", color: "Negro", size: "35-47", price: 44.99, rating: 4.4, searchQuery: "converse chuck 70" },
    { id: 33, brand: "Converse", name: "Converse One Star", color: "Verde", size: "35-47", price: 39.99, rating: 4.3, searchQuery: "converse one star" },
    { id: 34, brand: "Converse", name: "Converse Platform Chuck Taylor", color: "Rosa", size: "35-46", price: 49.99, rating: 4.4, searchQuery: "converse platform" },
    { id: 35, brand: "Converse", name: "Converse ERX 260", color: "Blanco/Negro", size: "35-47", price: 54.99, rating: 4.5, searchQuery: "converse erx" },
    { id: 36, brand: "Converse", name: "Converse JP Jack Purcell", color: "Azul", size: "35-47", price: 44.99, rating: 4.3, searchQuery: "converse jack purcell" },
    { id: 37, brand: "Converse", name: "Converse Renew Cotton", color: "Gris", size: "35-47", price: 39.99, rating: 4.2, searchQuery: "converse" },
    { id: 38, brand: "Converse", name: "Converse Kids Star Chevron", color: "Blanco", size: "28-39", price: 30.00, rating: 4.3, searchQuery: "converse kids" },
    { id: 39, brand: "Converse", name: "Converse Lift Canvas", color: "Negro", size: "35-46", price: 49.99, rating: 4.4, searchQuery: "converse lift" },
    { id: 40, brand: "Converse", name: "Converse Seasonal Color", color: "Naranja", size: "35-47", price: 34.99, rating: 4.2, searchQuery: "converse" },
    { id: 41, brand: "Vans", name: "Vans Old Skool", color: "Blanco/Negro", size: "35-47", price: 44.99, rating: 4.5, searchQuery: "vans old skool" },
    { id: 42, brand: "Vans", name: "Vans Authentic", color: "Blanco", size: "35-47", price: 39.99, rating: 4.4, searchQuery: "vans authentic" },
    { id: 43, brand: "Vans", name: "Vans SK8-Hi", color: "Rojo", size: "35-47", price: 49.99, rating: 4.5, searchQuery: "vans sk8 hi" },
    { id: 44, brand: "Vans", name: "Vans Era", color: "Negro", size: "35-47", price: 42.49, rating: 4.4, searchQuery: "vans era" },
    { id: 45, brand: "Vans", name: "Vans Slip-On", color: "Gris", size: "35-47", price: 39.99, rating: 4.3, searchQuery: "vans slip on" },
    { id: 46, brand: "Vans", name: "Vans Comfycush", color: "Blanco/Azul", size: "35-47", price: 49.99, rating: 4.6, searchQuery: "vans comfycush" },
    { id: 47, brand: "Vans", name: "Vans TNT Advanced", color: "Verde", size: "35-47", price: 44.99, rating: 4.4, searchQuery: "vans tnt" },
    { id: 48, brand: "Vans", name: "Vans Sk8-Hi Reissue", color: "Negro/Blanco", size: "35-47", price: 54.99, rating: 4.5, searchQuery: "vans sk8 hi" },
    { id: 49, brand: "Vans", name: "Vans Old Skool Pro", color: "Amarillo", size: "35-47", price: 49.99, rating: 4.4, searchQuery: "vans old skool" },
    { id: 50, brand: "Vans", name: "Vans Ultrarange", color: "Blanco", size: "35-47", price: 59.99, rating: 4.5, searchQuery: "vans ultrarange" },
    { id: 51, brand: "New Balance", name: "New Balance 574", color: "Gris", size: "35-47", price: 59.99, rating: 4.5, searchQuery: "new balance 574" },
    { id: 52, brand: "New Balance", name: "New Balance 990v5", color: "Negro", size: "36-47", price: 95.00, rating: 4.8, searchQuery: "new balance 990" },
    { id: 53, brand: "New Balance", name: "New Balance 327", color: "Blanco", size: "35-47", price: 54.99, rating: 4.5, searchQuery: "new balance 327" },
    { id: 54, brand: "New Balance", name: "New Balance 550", color: "Blanco/Azul", size: "35-47", price: 65.00, rating: 4.6, searchQuery: "new balance 550" },
    { id: 55, brand: "New Balance", name: "New Balance 2002R", color: "Gris", size: "35-47", price: 70.00, rating: 4.6, searchQuery: "new balance 2002r" },
    { id: 56, brand: "New Balance", name: "New Balance 1906", color: "Blanco/Negro", size: "35-47", price: 65.00, rating: 4.5, searchQuery: "new balance 1906" },
    { id: 57, brand: "New Balance", name: "New Balance 530", color: "Verde", size: "35-47", price: 49.99, rating: 4.4, searchQuery: "new balance 530" },
    { id: 58, brand: "New Balance", name: "New Balance 515", color: "Rosa", size: "35-46", price: 44.99, rating: 4.3, searchQuery: "new balance 515" },
    { id: 59, brand: "New Balance", name: "New Balance 725", color: "Negro", size: "35-47", price: 49.99, rating: 4.4, searchQuery: "new balance 725" },
    { id: 60, brand: "New Balance", name: "New Balance Fuelcell", color: "Amarillo", size: "35-47", price: 75.00, rating: 4.7, searchQuery: "new balance fuelcell" },
    { id: 61, brand: "Reebok", name: "Reebok Classic Leather", color: "Blanco", size: "35-47", price: 49.99, rating: 4.4, searchQuery: "reebok classic leather" },
    { id: 62, brand: "Reebok", name: "Reebok Club C", color: "Verde", size: "35-47", price: 44.99, rating: 4.3, searchQuery: "reebok club c" },
    { id: 63, brand: "Reebok", name: "Reebok Pump Omni Lite", color: "Negro/Rojo", size: "35-47", price: 59.99, rating: 4.5, searchQuery: "reebok pump" },
    { id: 64, brand: "Reebok", name: "Reebok Instapump Fury", color: "Blanco", size: "35-47", price: 65.00, rating: 4.6, searchQuery: "reebok instapump" },
    { id: 65, brand: "Reebok", name: "Reebok Insta Pump Fury", color: "Azul", size: "35-47", price: 70.00, rating: 4.5, searchQuery: "reebok pump fury" },
    { id: 66, brand: "Reebok", name: "Reebok Legacy", color: "Gris", size: "35-47", price: 49.99, rating: 4.3, searchQuery: "reebok legacy" },
    { id: 67, brand: "Reebok", name: "Reebok Question Mid", color: "Negro/Blanco", size: "40-47", price: 85.00, rating: 4.7, searchQuery: "reebok question" },
    { id: 68, brand: "Reebok", name: "Reebok Floatride", color: "Blanco/Azul", size: "35-47", price: 75.00, rating: 4.6, searchQuery: "reebok floatride" },
    { id: 69, brand: "Reebok", name: "Reebok EnergyLux", color: "Rosa", size: "35-46", price: 54.99, rating: 4.4, searchQuery: "reebok energylux" },
    { id: 70, brand: "Reebok", name: "Reebok Bolton", color: "Negro", size: "35-47", price: 59.99, rating: 4.4, searchQuery: "reebok bolton" },
    { id: 71, brand: "Saucony", name: "Saucony Jazz", color: "Blanco/Azul", size: "35-47", price: 39.99, rating: 4.3, searchQuery: "saucony jazz" },
    { id: 72, brand: "Saucony", name: "Saucony Shadow", color: "Gris", size: "35-47", price: 44.99, rating: 4.4, searchQuery: "saucony shadow" },
    { id: 73, brand: "Saucony", name: "Saucony Grid Web", color: "Negro", size: "35-47", price: 54.99, rating: 4.5, searchQuery: "saucony grid" },
    { id: 74, brand: "Saucony", name: "Saucony Aya", color: "Blanco", size: "35-47", price: 49.99, rating: 4.4, searchQuery: "saucony aya" },
    { id: 75, brand: "Saucony", name: "Saucony Endorphin Speed", color: "Negro/Amarillo", size: "35-47", price: 70.00, rating: 4.7, searchQuery: "saucony endorphin" },
    { id: 76, brand: "Saucony", name: "Saucony Ride", color: "Blanco/Verde", size: "35-47", price: 65.00, rating: 4.6, searchQuery: "saucony ride" },
    { id: 77, brand: "Saucony", name: "Saucony Kinvara", color: "Rojo", size: "35-47", price: 59.99, rating: 4.5, searchQuery: "saucony kinvara" },
    { id: 78, brand: "Saucony", name: "Saucony Echelon", color: "Azul", size: "35-47", price: 59.99, rating: 4.5, searchQuery: "saucony echelon" },
    { id: 79, brand: "Saucony", name: "Saucony Tornado", color: "Naranja", size: "35-47", price: 44.99, rating: 4.2, searchQuery: "saucony tornado" },
    { id: 80, brand: "Saucony", name: "Saucony DXN Vintage", color: "Blanco/Negro", size: "35-47", price: 49.99, rating: 4.3, searchQuery: "saucony dxn" },
    { id: 81, brand: "Asics", name: "Asics Gel-Lyte III", color: "Gris", size: "35-47", price: 59.99, rating: 4.6, searchQuery: "asics gel lyte" },
    { id: 82, brand: "Asics", name: "Asics Gel-Kayano", color: "Negro", size: "35-47", price: 80.00, rating: 4.7, searchQuery: "asics gel kayano" },
    { id: 83, brand: "Asics", name: "Asics Gel-Nimbus", color: "Azul", size: "35-47", price: 90.00, rating: 4.8, searchQuery: "asics gel nimbus" },
    { id: 84, brand: "Asics", name: "Asics GT-II", color: "Blanco/Rojo", size: "35-47", price: 65.00, rating: 4.5, searchQuery: "asics gt" },
    { id: 85, brand: "Asics", name: "Asics Novablast", color: "Amarillo", size: "35-47", price: 70.00, rating: 4.6, searchQuery: "asics novablast" },
    { id: 86, brand: "Asics", name: "Asics Gel-Contend", color: "Gris/Azul", size: "35-47", price: 49.99, rating: 4.4, searchQuery: "asics gel contend" },
    { id: 87, brand: "Asics", name: "Asics Gel-Pulse", color: "Blanco", size: "35-47", price: 54.99, rating: 4.4, searchQuery: "asics gel pulse" },
    { id: 88, brand: "Asics", name: "Asics Hypergel-Sai", color: "Negro/Blanco", size: "35-47", price: 75.00, rating: 4.5, searchQuery: "asics hypergel" },
    { id: 89, brand: "Asics", name: "Asics Gel-Lyte V", color: "Rosa", size: "35-46", price: 65.00, rating: 4.5, searchQuery: "asics gel lyte v" },
    { id: 90, brand: "Asics", name: "Asics Cumulus", color: "Naranja", size: "35-47", price: 70.00, rating: 4.6, searchQuery: "asics cumulus" },
    { id: 91, brand: "Salomon", name: "Salomon XA Pro 3D", color: "Negro", size: "35-47", price: 75.00, rating: 4.7, searchQuery: "salomon xa pro" },
    { id: 92, brand: "Salomon", name: "Salomon Speedcross", color: "Gris", size: "35-47", price: 65.00, rating: 4.6, searchQuery: "salomon speedcross" },
    { id: 93, brand: "Salomon", name: "Salomon Shoes Trail", color: "Blanco/Negro", size: "35-47", price: 70.00, rating: 4.6, searchQuery: "salomon trail" },
    { id: 94, brand: "Salomon", name: "Salomon Outbound GTX", color: "Marrón", size: "35-47", price: 90.00, rating: 4.7, searchQuery: "salomon outbound" },
    { id: 95, brand: "Salomon", name: "Salomon Wings Pro 2", color: "Azul", size: "35-47", price: 75.00, rating: 4.5, searchQuery: "salomon wings" },
    { id: 96, brand: "Salomon", name: "Salomon Sense Ride", color: "Rojo", size: "35-47", price: 80.00, rating: 4.6, searchQuery: "salomon sense" },
    { id: 97, brand: "Salomon", name: "Salomon Outbounds", color: "Verde", size: "35-47", price: 75.00, rating: 4.5, searchQuery: "salomon" },
    { id: 98, brand: "Salomon", name: "Salomon Ultra Pro", color: "Naranja", size: "35-47", price: 85.00, rating: 4.7, searchQuery: "salomon ultra" },
    { id: 99, brand: "Salomon", name: "Salomon Speedcross 5 GTX", color: "Negro/Gris", size: "35-47", price: 75.00, rating: 4.6, searchQuery: "salomon speedcross" },
    { id: 100, brand: "Salomon", name: "Salomon Quest 4D", color: "Marrón/Negro", size: "35-47", price: 95.00, rating: 4.8, searchQuery: "salomon quest" },
    { id: 101, brand: "Columbia", name: "Columbia Montrail Trinity", color: "Negro", size: "35-47", price: 70.00, rating: 4.5, searchQuery: "columbia hiking" },
    { id: 102, brand: "Columbia", name: "Columbia IVO Trail", color: "Gris", size: "35-47", price: 65.00, rating: 4.4, searchQuery: "columbia ivo" },
    { id: 103, brand: "Columbia", name: "Columbia Peakfreak", color: "Naranja/Negro", size: "35-47", price: 85.00, rating: 4.6, searchQuery: "columbia peakfreak" },
    { id: 104, brand: "Columbia", name: "Columbia Drainmaker", color: "Blanco/Azul", size: "35-47", price: 59.99, rating: 4.4, searchQuery: "columbia drainmaker" },
    { id: 105, brand: "Columbia", name: "Columbia Firecamp", color: "Marrón", size: "35-47", price: 49.99, rating: 4.3, searchQuery: "columbia firecamp" },
    { id: 106, brand: "Columbia", name: "Columbia Redmond", color: "Negro", size: "35-47", price: 54.99, rating: 4.4, searchQuery: "columbia redmond" },
    { id: 107, brand: "Columbia", name: "Columbia Waverunner", color: "Azul", size: "35-47", price: 65.00, rating: 4.5, searchQuery: "columbia waverunner" },
    { id: 108, brand: "Columbia", name: "Columbia Newton Ridge", color: "Marrón/Negro", size: "35-47", price: 70.00, rating: 4.5, searchQuery: "columbia newton" },
    { id: 109, brand: "Columbia", name: "Columbia Grand Turns", color: "Gris/Azul", size: "35-47", price: 75.00, rating: 4.6, searchQuery: "columbia" },
    { id: 110, brand: "Columbia", name: "Columbia Vitesse", color: "Rojo", size: "35-47", price: 54.99, rating: 4.3, searchQuery: "columbia" },
    { id: 111, brand: "Mizuno", name: "Mizuno Wave Rider", color: "Negro/Azul", size: "35-47", price: 75.00, rating: 4.6, searchQuery: "mizuno wave rider" },
    { id: 112, brand: "Mizuno", name: "Mizuno Wave Inspire", color: "Gris", size: "35-47", price: 70.00, rating: 4.5, searchQuery: "mizuno wave inspire" },
    { id: 113, brand: "Mizuno", name: "Mizuno Wave Creation", color: "Blanco", size: "35-47", price: 80.00, rating: 4.6, searchQuery: "mizuno wave" },
    { id: 114, brand: "Mizuno", name: "Mizuno Wave Prophecy", color: "Naranja", size: "35-47", price: 85.00, rating: 4.7, searchQuery: "mizuno wave prophecy" },
    { id: 115, brand: "Mizuno", name: "Mizuno Sky Medal", color: "Rojo", size: "35-47", price: 59.99, rating: 4.4, searchQuery: "mizuno sky" },
    { id: 116, brand: "Mizuno", name: "Mizuno Volleyball Shoes", color: "Negro", size: "35-47", price: 65.00, rating: 4.5, searchQuery: "mizuno volleyball" },
    { id: 117, brand: "Mizuno", name: "Mizuno Wave Momentum", color: "Blanco/Azul", size: "35-47", price: 70.00, rating: 4.5, searchQuery: "mizuno wave momentum" },
    { id: 118, brand: "Mizuno", name: "Mizuno Wave Exceed", color: "Amarillo", size: "35-47", price: 65.00, rating: 4.4, searchQuery: "mizuno exceed" },
    { id: 119, brand: "Mizuno", name: "Mizuno Thunder Blade", color: "Rojo/Negro", size: "35-47", price: 49.99, rating: 4.2, searchQuery: "mizuno thunder" },
    { id: 120, brand: "Mizuno", name: "Mizuno Cyclone Speed", color: "Verde", size: "35-47", price: 49.99, rating: 4.3, searchQuery: "mizuno cyclone" },
    { id: 121, brand: "Brooks", name: "Brooks Ghost", color: "Negro/Gris", size: "35-47", price: 75.00, rating: 4.7, searchQuery: "brooks ghost" },
    { id: 122, brand: "Brooks", name: "Brooks Adrenaline", color: "Azul", size: "35-47", price: 70.00, rating: 4.6, searchQuery: "brooks adrenaline" },
    { id: 123, brand: "Brooks", name: "Brooks Ravenna", color: "Gris", size: "35-47", price: 70.00, rating: 4.6, searchQuery: "brooks ravenna" },
    { id: 124, brand: "Brooks", name: "Brooks Glycerin", color: "Blanco", size: "35-47", price: 85.00, rating: 4.7, searchQuery: "brooks glycerin" },
    { id: 125, brand: "Brooks", name: "Brooks Launch", color: "Negro", size: "35-47", price: 59.99, rating: 4.5, searchQuery: "brooks launch" },
    { id: 126, brand: "Brooks", name: "Brooks Beast", color: "Marrón", size: "35-47", price: 80.00, rating: 4.6, searchQuery: "brooks beast" },
    { id: 127, brand: "Brooks", name: "Brooks Addiction", color: "Negro/Azul", size: "35-47", price: 75.00, rating: 4.5, searchQuery: "brooks addiction" },
    { id: 128, brand: "Brooks", name: "Brooks Transcend", color: "Gris/Rojo", size: "35-47", price: 85.00, rating: 4.7, searchQuery: "brooks transcend" },
    { id: 129, brand: "Brooks", name: "Brooks Caldera", color: "Verde", size: "35-47", price: 75.00, rating: 4.5, searchQuery: "brooks trail" },
    { id: 130, brand: "Brooks", name: "Brooks Catamount", color: "Naranja", size: "35-47", price: 70.00, rating: 4.4, searchQuery: "brooks catamount" },
    { id: 131, brand: "Hoka", name: "Hoka Clifton", color: "Blanco", size: "35-47", price: 80.00, rating: 4.8, searchQuery: "hoka clifton" },
    { id: 132, brand: "Hoka", name: "Hoka Bondi", color: "Negro", size: "35-47", price: 90.00, rating: 4.8, searchQuery: "hoka bondi" },
    { id: 133, brand: "Hoka", name: "Hoka Rincon", color: "Azul", size: "35-47", price: 70.00, rating: 4.7, searchQuery: "hoka rincon" },
    { id: 134, brand: "Hoka", name: "Hoka Arahi", color: "Gris", size: "35-47", price: 80.00, rating: 4.7, searchQuery: "hoka arahi" },
    { id: 135, brand: "Hoka", name: "Hoka Tor Ultra Hi", color: "Marrón/Naranja", size: "35-47", price: 85.00, rating: 4.7, searchQuery: "hoka tor ultra" },
    { id: 136, brand: "Hoka", name: "Hoka Speedgoat", color: "Negro/Amarillo", size: "35-47", price: 85.00, rating: 4.7, searchQuery: "hoka speedgoat" },
    { id: 137, brand: "Hoka", name: "Hoka Mach", color: "Blanco/Negro", size: "35-47", price: 70.00, rating: 4.6, searchQuery: "hoka mach" },
    { id: 138, brand: "Hoka", name: "Hoka Cavu", color: "Azul/Blanco", size: "35-47", price: 80.00, rating: 4.7, searchQuery: "hoka cavu" },
    { id: 139, brand: "Hoka", name: "Hoka Stinson ATR", color: "Gris/Verde", size: "35-47", price: 85.00, rating: 4.6, searchQuery: "hoka stinson" },
    { id: 140, brand: "Hoka", name: "Hoka Akasa", color: "Rosa", size: "35-46", price: 75.00, rating: 4.6, searchQuery: "hoka akasa" },
    { id: 141, brand: "Altra", name: "Altra Torin", color: "Negro/Gris", size: "35-47", price: 75.00, rating: 4.6, searchQuery: "altra torin" },
    { id: 142, brand: "Altra", name: "Altra Lone Peak", color: "Azul", size: "35-47", price: 70.00, rating: 4.5, searchQuery: "altra lone peak" },
    { id: 143, brand: "Altra", name: "Altra Paradigm", color: "Gris", size: "35-47", price: 65.00, rating: 4.5, searchQuery: "altra paradigm" },
    { id: 144, brand: "Altra", name: "Altra Rivera", color: "Verde", size: "35-47", price: 54.99, rating: 4.4, searchQuery: "altra rivera" },
    { id: 145, brand: "Altra", name: "Altra Vanish", color: "Negro", size: "35-47", price: 59.99, rating: 4.5, searchQuery: "altra vanish" },
    { id: 146, brand: "Altra", name: "Altra Escalante", color: "Rojo", size: "35-47", price: 65.00, rating: 4.5, searchQuery: "altra escalante" },
    { id: 147, brand: "Altra", name: "Altra Timp", color: "Naranja", size: "35-47", price: 80.00, rating: 4.6, searchQuery: "altra timp" },
    { id: 148, brand: "Altra", name: "Altra Katal", color: "Blanco/Azul", size: "35-47", price: 65.00, rating: 4.5, searchQuery: "altra katal" },
    { id: 149, brand: "Altra", name: "Altra Olympus", color: "Amarillo", size: "35-47", price: 85.00, rating: 4.6, searchQuery: "altra olympus" },
    { id: 150, brand: "Altra", name: "Altra Precept", color: "Gris/Rojo", size: "35-47", price: 70.00, rating: 4.5, searchQuery: "altra precept" },
    { id: 151, brand: "Merrell", name: "Merrell Moab 2", color: "Marrón", size: "35-47", price: 70.00, rating: 4.7, searchQuery: "merrell moab" },
    { id: 152, brand: "Merrell", name: "Merrell Moab Venture", color: "Negro/Gris", size: "35-47", price: 65.00, rating: 4.6, searchQuery: "merrell moab venture" },
    { id: 153, brand: "Merrell", name: "Merrell Bare Access", color: "Verde", size: "35-47", price: 59.99, rating: 4.5, searchQuery: "merrell bare access" },
    { id: 154, brand: "Merrell", name: "Merrell Allout Peak", color: "Negro", size: "35-47", price: 65.00, rating: 4.5, searchQuery: "merrell allout peak" },
    { id: 155, brand: "Merrell", name: "Merrell Trail Runner", color: "Azul", size: "35-47", price: 59.99, rating: 4.4, searchQuery: "merrell trail" },
    { id: 156, brand: "Merrell", name: "Merrell Jungle Moc", color: "Marrón/Blanco", size: "35-47", price: 49.99, rating: 4.3, searchQuery: "merrell jungle" },
    { id: 157, brand: "Merrell", name: "Merrell Glove", color: "Gris", size: "35-47", price: 59.99, rating: 4.4, searchQuery: "merrell glove" },
    { id: 158, brand: "Merrell", name: "Merrell Agility Peak Flex", color: "Rojo/Negro", size: "35-47", price: 65.00, rating: 4.5, searchQuery: "merrell agility" },
    { id: 159, brand: "Merrell", name: "Merrell Siren", color: "Rosa", size: "35-46", price: 59.99, rating: 4.4, searchQuery: "merrell siren" },
    { id: 160, brand: "Merrell", name: "Merrell Capra", color: "Naranja/Negro", size: "35-47", price: 75.00, rating: 4.6, searchQuery: "merrell capra" },
    { id: 161, brand: "Timberland", name: "Timberland Classic Boots", color: "Marrón", size: "35-47", price: 85.00, rating: 4.6, searchQuery: "timberland boots" },
    { id: 162, brand: "Timberland", name: "Timberland Euro Hiker", color: "Negro/Marrón", size: "35-47", price: 80.00, rating: 4.5, searchQuery: "timberland euro hiker" },
    { id: 163, brand: "Timberland", name: "Timberland Chocorua Trail", color: "Gris", size: "35-47", price: 70.00, rating: 4.5, searchQuery: "timberland trail" },
    { id: 164, brand: "Timberland", name: "Timberland Hiking Boot", color: "Tan", size: "35-47", price: 75.00, rating: 4.5, searchQuery: "timberland hiking" },
    { id: 165, brand: "Timberland", name: "Timberland Nellie Boot", color: "Negro", size: "35-46", price: 75.00, rating: 4.4, searchQuery: "timberland nellie" },
    { id: 166, brand: "Timberland", name: "Timberland Field Boot", color: "Marrón", size: "35-47", price: 90.00, rating: 4.6, searchQuery: "timberland field" },
    { id: 167, brand: "Timberland", name: "Timberland Adventure", color: "Beige/Negro", size: "35-47", price: 70.00, rating: 4.4, searchQuery: "timberland" },
    { id: 168, brand: "Timberland", name: "Timberland Leather Boot", color: "Rojo/Marrón", size: "35-47", price: 80.00, rating: 4.5, searchQuery: "timberland leather" },
    { id: 169, brand: "Timberland", name: "Timberland Casual Hiker", color: "Gris/Negro", size: "35-47", price: 65.00, rating: 4.3, searchQuery: "timberland hiker" },
    { id: 170, brand: "Timberland", name: "Timberland 6-Inch Premium", color: "Marrón", size: "35-47", price: 90.00, rating: 4.6, searchQuery: "timberland 6 inch" },
    { id: 171, brand: "Keen", name: "Keen Targhee", color: "Marrón", size: "35-47", price: 75.00, rating: 4.5, searchQuery: "keen targhee" },
    { id: 172, brand: "Keen", name: "Keen Voyageur", color: "Gris/Negro", size: "35-47", price: 70.00, rating: 4.4, searchQuery: "keen voyageur" },
    { id: 173, brand: "Keen", name: "Keen Newport", color: "Sandalia", size: "35-47", price: 49.99, rating: 4.3, searchQuery: "keen newport" },
    { id: 174, brand: "Keen", name: "Keen Terradora", color: "Negro/Gris", size: "35-46", price: 65.00, rating: 4.4, searchQuery: "keen terradora" },
    { id: 175, brand: "Keen", name: "Keen Durand", color: "Café", size: "35-47", price: 75.00, rating: 4.5, searchQuery: "keen durand" },
    { id: 176, brand: "Keen", name: "Keen Moro", color: "Negro", size: "35-47", price: 75.00, rating: 4.5, searchQuery: "keen moro" },
    { id: 177, brand: "Keen", name: "Keen Saltzman", color: "Marrón/Naranja", size: "35-47", price: 80.00, rating: 4.6, searchQuery: "keen saltzman" },
    { id: 178, brand: "Keen", name: "Keen Oakland", color: "Negro/Marrón", size: "35-47", price: 70.00, rating: 4.4, searchQuery: "keen oakland" },
    { id: 179, brand: "Keen", name: "Keen Hiking Shoe", color: "Verde/Gris", size: "35-47", price: 65.00, rating: 4.3, searchQuery: "keen hiking" },
    { id: 180, brand: "Keen", name: "Keen Trail Runner", color: "Azul/Negro", size: "35-47", price: 70.00, rating: 4.4, searchQuery: "keen trail" },
    { id: 181, brand: "Sperry", name: "Sperry Gold Cup", color: "Marrón", size: "35-47", price: 90.00, rating: 4.6, searchQuery: "sperry gold cup" },
    { id: 182, brand: "Sperry", name: "Sperry Boat Shoe", color: "Negro", size: "35-47", price: 49.99, rating: 4.4, searchQuery: "sperry boat" },
    { id: 183, brand: "Sperry", name: "Sperry Authentic", color: "Azul/Blanco", size: "35-47", price: 54.99, rating: 4.4, searchQuery: "sperry authentic" },
    { id: 184, brand: "Sperry", name: "Sperry Top-Sider", color: "Beige", size: "35-47", price: 59.99, rating: 4.5, searchQuery: "sperry top-sider" },
    { id: 185, brand: "Sperry", name: "Sperry Marine Shoe", color: "Rojo/Blanco", size: "35-47", price: 49.99, rating: 4.3, searchQuery: "sperry marine" },
    { id: 186, brand: "Sperry", name: "Sperry A/O 2-Eye", color: "Blanco", size: "35-47", price: 65.00, rating: 4.5, searchQuery: "sperry a/o" },
    { id: 187, brand: "Sperry", name: "Sperry Billfish", color: "Tan", size: "35-47", price: 59.99, rating: 4.4, searchQuery: "sperry billfish" },
    { id: 188, brand: "Sperry", name: "Sperry Firefish", color: "Rosa", size: "35-46", price: 54.99, rating: 4.3, searchQuery: "sperry firefish" },
    { id: 189, brand: "Sperry", name: "Sperry Authentic Original", color: "Verde", size: "35-47", price: 49.99, rating: 4.2, searchQuery: "sperry" },
    { id: 190, brand: "Sperry", name: "Sperry Captain", color: "Azul Marino", size: "35-47", price: 65.00, rating: 4.4, searchQuery: "sperry captain" },
    { id: 191, brand: "Columbia", name: "Columbia Casual Runner", color: "Gris", size: "35-47", price: 44.99, rating: 4.2, searchQuery: "columbia runner" },
    { id: 192, brand: "Columbia", name: "Columbia Street Running", color: "Blanco/Negro", size: "35-47", price: 49.99, rating: 4.3, searchQuery: "columbia running" },
    { id: 193, brand: "Columbia", name: "Columbia Waterproof Trail", color: "Negro/Gris", size: "35-47", price: 59.99, rating: 4.4, searchQuery: "columbia waterproof" },
    { id: 194, brand: "Columbia", name: "Columbia Urban Hiker", color: "Beige", size: "35-47", price: 54.99, rating: 4.3, searchQuery: "columbia urban" },
    { id: 195, brand: "Columbia", name: "Columbia All Terrain", color: "Marrón", size: "35-47", price: 65.00, rating: 4.5, searchQuery: "columbia all terrain" },
    { id: 196, brand: "Puma", name: "Puma Creature", color: "Negro/Rojo", size: "35-47", price: 54.99, rating: 4.4, searchQuery: "puma creature" },
    { id: 197, brand: "Puma", name: "Puma Wild Rider", color: "Blanco", size: "35-47", price: 59.99, rating: 4.5, searchQuery: "puma wild rider" },
    { id: 198, brand: "Puma", name: "Puma RS-0", color: "Azul/Amarillo", size: "35-47", price: 65.00, rating: 4.5, searchQuery: "puma rs-0" },
    { id: 199, brand: "Puma", name: "Puma Cell Alien", color: "Verde/Naranja", size: "35-47", price: 70.00, rating: 4.6, searchQuery: "puma cell alien" },
    { id: 200, brand: "Puma", name: "Puma Centaur", color: "Negro", size: "35-47", price: 49.99, rating: 4.3, searchQuery: "puma centaur" },
    { id: 201, brand: "Nike", name: "Nike Revolution", color: "Gris/Negro", size: "35-47", price: 34.99, rating: 4.1, searchQuery: "nike revolution" },
    { id: 202, brand: "Nike", name: "Nike Flex", color: "Blanco/Azul", size: "35-47", price: 39.99, rating: 4.2, searchQuery: "nike flex" },
    { id: 203, brand: "Nike", name: "Nike Winflo", color: "Negro", size: "35-47", price: 44.99, rating: 4.3, searchQuery: "nike winflo" },
    { id: 204, brand: "Nike", name: "Nike Downshifter", color: "Gris", size: "35-47", price: 39.99, rating: 4.2, searchQuery: "nike downshifter" },
    { id: 205, brand: "Nike", name: "Nike Tanjun", color: "Blanco", size: "35-47", price: 42.49, rating: 4.3, searchQuery: "nike tanjun" },
    { id: 206, brand: "Nike", name: "Nike Quest", color: "Negro/Gris", size: "35-47", price: 49.99, rating: 4.3, searchQuery: "nike quest" },
    { id: 207, brand: "Nike", name: "Nike Nightgazer", color: "Verde", size: "35-47", price: 49.99, rating: 4.2, searchQuery: "nike nightgazer" },
    { id: 208, brand: "Nike", name: "Nike In-Season TR", color: "Rojo/Blanco", size: "35-47", price: 49.99, rating: 4.3, searchQuery: "nike in season" },
    { id: 209, brand: "Nike", name: "Nike Kaishi", color: "Azul", size: "35-47", price: 44.99, rating: 4.2, searchQuery: "nike kaishi" },
    { id: 210, brand: "Nike", name: "Nike Odyssey React", color: "Naranja/Negro", size: "35-47", price: 65.00, rating: 4.5, searchQuery: "nike odyssey react" },
    { id: 211, brand: "Adidas", name: "Adidas Cloud Foam", color: "Blanco/Negro", size: "35-47", price: 44.99, rating: 4.3, searchQuery: "adidas cloudfoam" },
    { id: 212, brand: "Adidas", name: "Adidas Questar", color: "Gris", size: "35-47", price: 49.99, rating: 4.3, searchQuery: "adidas questar" },
    { id: 213, brand: "Adidas", name: "Adidas Element Race", color: "Negro", size: "35-47", price: 54.99, rating: 4.4, searchQuery: "adidas element" },
    { id: 214, brand: "Adidas", name: "Adidas Duramo", color: "Azul", size: "35-47", price: 39.99, rating: 4.1, searchQuery: "adidas duramo" },
    { id: 215, brand: "Adidas", name: "Adidas Cloudfoam Pure", color: "Blanco", size: "35-47", price: 49.99, rating: 4.3, searchQuery: "adidas cloudfoam pure" },
    { id: 216, brand: "Adidas", name: "Adidas Pureboost", color: "Negro/Rojo", size: "35-47", price: 80.00, rating: 4.6, searchQuery: "adidas pureboost" },
    { id: 217, brand: "Adidas", name: "Adidas Solarglide", color: "Gris/Amarillo", size: "35-47", price: 75.00, rating: 4.5, searchQuery: "adidas solarglide" },
    { id: 218, brand: "Adidas", name: "Adidas Terrex Swift", color: "Verde", size: "35-47", price: 70.00, rating: 4.5, searchQuery: "adidas terrex swift" },
    { id: 219, brand: "Adidas", name: "Adidas Terrex Agravic", color: "Negro/Azul", size: "35-47", price: 75.00, rating: 4.6, searchQuery: "adidas terrex agravic" },
    { id: 220, brand: "Adidas", name: "Adidas Alphabounce", color: "Blanco/Rosa", size: "35-46", price: 59.99, rating: 4.4, searchQuery: "adidas alphabounce" },
    { id: 221, brand: "Adidas", name: "Adidas Climacool", color: "Azul/Blanco", size: "35-47", price: 49.99, rating: 4.2, searchQuery: "adidas climacool" },
    { id: 222, brand: "Adidas", name: "Adidas Alphabounce Beyond", color: "Negro", size: "35-47", price: 65.00, rating: 4.5, searchQuery: "adidas alphabounce beyond" }
];

function getSneakers() { return sneakers; }
function searchSneakers(query) { return sneakers.filter(s => s.name.toLowerCase().includes(query.toLowerCase()) || s.brand.toLowerCase().includes(query.toLowerCase())); }
function filterByBrand(brand) { if (!brand) return sneakers; return sneakers.filter(s => s.brand === brand); }
function filterByPrice(maxPrice) { return sneakers.filter(s => s.price <= maxPrice); }
function filterByColor(color) { if (!color) return sneakers; return sneakers.filter(s => s.color.toLowerCase().includes(color.toLowerCase())); }
function getBrands() { const brands = [...new Set(sneakers.map(s => s.brand))]; return brands.sort(); }
function getColors() { const colors = new Set(); sneakers.forEach(s => { s.color.split('/').forEach(c => colors.add(c.trim())); }); return Array.from(colors).sort(); }

// Function to get sneaker image from Unsplash API
async function getSneakerImage(searchQuery) {
    try {
        const response = await fetch(`https://api.unsplash.com/search/photos?query=${encodeURIComponent(searchQuery)}&client_id=o2LfPR_aLEPB1cPPxiBpGBBxn2QwzWJdbXPjPw_JL4E&per_page=1`);
        if (!response.ok) throw new Error('API Error');
        const data = await response.json();
        if (data.results && data.results.length > 0) {
            return data.results[0].urls.regular;
        }
        return null;
    } catch (error) {
        console.error('Error fetching image:', error);
        return null;
    }
}
